version: '3.4'
services:

########################################################################################
  # MQ
  ########################################################################################
  rabbitmq:
    image: rabbitmq:3-management-alpine
  ########################################################################################
  # REDIS
  ########################################################################################
  redis:
    image: redis:alpine
  ########################################################################################
  # SQL SERVER
  ########################################################################################
  sqldata:
    image: mcr.microsoft.com/azure-sql-edge
  ########################################################################################
  # SEQ
  ########################################################################################
  seq:
    image: datalust/seq:latest
  ########################################################################################
  # RpiService
  ########################################################################################
  rpi.service:
    image: ${DOCKER_REGISTRY-}rpi.service
    build:
      context: .
      dockerfile: src/services/RpiService/Dockerfile
    depends_on:
      - redis
  rpi.service-dapr:
    image: "daprio/daprd:1.9.0"
    network_mode: "service:rpi.service"
    #network_mode: "service:bouvet.rule.engine.service"
    depends_on:
      - rpi.service
  
  ########################################################################################
  # WEB STATUS
  ########################################################################################
  webstatus:
    image: ${REGISTRY:-eshopdapr}/webstatus:${TAG:-latest}
    build:
      context: .
      dockerfile: src/web/webStatus/Dockerfile
  ########################################################################################
  # DAPR-PLACEMENT
  ########################################################################################
  dapr-placement:
    image: "daprio/dapr:1.9.0"
########################################################################################
# NETWORKS
########################################################################################
networks:
  hello-dapr:
