version: '3.4'
services:
  ########################################################################################
  # MQ
  ########################################################################################  
  rabbitmq:
    ports:
      - "5672:5672"
  ########################################################################################
  # REDIS
  ########################################################################################
  redis:
    image: redis:alpine
    ports:
      - "5379:6379"
  ########################################################################################
  # SQL SERVER
  ########################################################################################
  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5233:1433"
    volumes:
      - rpi.service-sqldata:/var/opt/mssql
  ########################################################################################
  # SEQ
  ########################################################################################
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:82"
  ########################################################################################
  # Rpi Service
  ########################################################################################
  rpi.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ApiGatewayUrlExternal=http://${RpiService_EXTERNAL_DNS_NAME_OR_IP}:5205
      - IdentityUrlExternal=http://${RpiService_EXTERNAL_DNS_NAME_OR_IP}:5109
      - SeqServerUrl=http://seq
    ports:
      - "5210:80"
      - "50001:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  #~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~
  rpi.service-dapr:
    command:
      [
        "./daprd",
        "-app-id", "rpi.service",
        "-app-port", "80",
        "-log-level", "debug",
        "-placement-host-address", "dapr-placement:50000",
        "-components-path", "/components",
        "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
  ########################################################################################
  # Web UI
  # The UI that demostrate the service inocvatio and pub/sub between 
  # C# <-> JS
  ########################################################################################
  ui.service:
    environment:
      - ApiGatewayUrlExternal=http://${RpiService_EXTERNAL_DNS_NAME_OR_IP}:5205
      - IdentityUrlExternal=http://${RpiService_EXTERNAL_DNS_NAME_OR_IP}:5109
      - SeqServerUrl=http://seq
    ports:
      - "5173:90"
      - "50002:50002"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  ui.service-dapr:
    command:
      ["./daprd",
        "-app-id", "ui",
        "-app-port", "90",
        "-placement-host-address","dapr-placement:50000", # Dapr's placement service can be reach via the docker DNS entry
        "-components-path","/components",
        "-config", "/configuration/config.yaml"
      ]
    volumes:
      # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
# Attach the nodeapp-dapr service to the nodeapp network namespace
    network_mode: "service:ui.service" 
  ########################################################################################
  # WebStatus
  #######################################################################################
  webstatus:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:100
      - HealthChecksUI__HealthChecks__0__Name=RPI SERVICE
      - HealthChecksUI__HealthChecks__0__Uri=http://rpi-service/hc
      - HealthChecksUI__HealthChecks__1__Name=UI SERVICE
      - HealthChecksUI__HealthChecks__1__Uri=http://ui-service/hc
    ports:
      - "5205:100"
  ########################################################################################
  # DAPR-PLACEMENT
  ########################################################################################
  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"
volumes:
  rpi.service-sqldata:
    external: false
  rpi.service-nosqldata:
    external: false
  rpi.service-basketdata:
    external: false
