version: '3.4'
# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The ESHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     ESHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
services:
  rabbitmq:
    ports:
      - "5672:5672"
  redis:
    image: redis:alpine
    ports:
      - "5379:6379"
  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5233:1433"
    volumes:
      - rpi.service-sqldata:/var/opt/mssql
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
  ########################################################################################
  # Rpi Service
  ########################################################################################
  rpi.service:  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ApiGatewayUrlExternal=http://${RpiService_EXTERNAL_DNS_NAME_OR_IP}:5202
      - IdentityUrlExternal=http://${RpiService_EXTERNAL_DNS_NAME_OR_IP}:5105
      - SeqServerUrl=http://seq
    ports:
      - "5210:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      
  rpi.service-dapr:
    command:
      [
        "./daprd",
        "-app-id",
        "rpi.service",
        "-app-port",
        "80",
        "-log-level",
        "debug",
        "-placement-host-address",
        "dapr-placement:50000",
        "-components-path",
        "/components",
        "-config",
        "/configuration/ruleengine-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
  ########################################################################################
  # WebStatus
  #######################################################################################
  webstatus:
      environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=rpi.service
      - HealthChecksUI__HealthChecks__0__Uri=http://rpi.service/hc
      #- HealthChecksUI__HealthChecks__1__Name=bouvet.cv.service
      #- HealthChecksUI__HealthChecks__1__Uri=http://catalog-api/hc
      #- HealthChecksUI__HealthChecks__2__Name=bouvet.notification.service
      #- HealthChecksUI__HealthChecks__2__Uri=http://bouvet.notification.service/hc
      #- HealthChecksUI__HealthChecks__3__Name=bouvet.rule.engine.service
      #- HealthChecksUI__HealthChecks__3__Uri=http://bouvet.rule.engine.service/hc
      ports:
        - "5200:80"
  ########################################################################################
  # DAPR-PLACEMENT
  ########################################################################################
  dapr-placement:
      command:
        [
          "./placement",
          "-port",
          "50000",
          "-log-level",
          "debug"
        ]
      ports:
        - "50000:50000"
volumes:
  rpi.service-sqldata:
    external: false
  rpi.service-nosqldata:
    external: false
  rpi.service-basketdata:
    external: false
