apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rpi-state
  namespace: rpi.service
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    secretKeyRef:
      name: State.RedisPassword
      key: State.RedisPassword
  - name: actorStateStore
    value: "true"
auth:
  secretStore: ruleenginedapr-secretstore
scopes:
- bouvet.cv.service
- cv.partner.service
- bouvet.notification.service
- bouvet.rule.engine.service
